use_default_settings: true

general:
  debug: false
  instance_name: "Aurelia Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "pt-BR"
  languages:
    - pt-BR
    - en

server:
  base_url: ""
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "aurelia-searxng-homelab-secret"
  limiter: false

ui:
  static_use_hash: false
  default_theme: simple
  default_locale: "pt-BR"

engines:
  - name: google
    engine: google
    categories: general
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
  - name: github
    engine: github
    shortcut: gh

outgoing:
  request_timeout: 10.0
  useragent_suffix: ""
  max_request_timeout: 30.0
