package llm

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/kocar/aurelia/internal/agent"
)

type stubCodexCaller struct {
	name string
	args map[string]any
	resp *codexToolResponse
	err  error
}

func (s *stubCodexCaller) CallTool(_ context.Context, name string, args map[string]any) (*codexToolResponse, error) {
	s.name = name
	s.args = args
	if s.err != nil {
		return nil, s.err
	}
	return s.resp, nil
}

func (s *stubCodexCaller) Close() error { return nil }

func TestCodexCLIProvider_FirstCallStartsCodexSession(t *testing.T) {
	caller := &stubCodexCaller{
		resp: &codexToolResponse{
			Content:  `{"content":"done","reasoning_content":"short","tool_calls":[]}`,
			ThreadID: "thread-1",
		},
	}
	provider := &CodexCLIProvider{
		model:   "gpt-5.4",
		caller:  caller,
		threads: make(map[string]string),
	}

	ctx := agent.WithRunContext(context.Background(), "run-1")
	resp, err := provider.GenerateContent(ctx, "sys", []agent.Message{{Role: "user", Content: "oi"}}, []agent.Tool{{Name: "read_file"}})
	if err != nil {
		t.Fatalf("GenerateContent() error = %v", err)
	}
	if resp.Content != "done" {
		t.Fatalf("Content = %q", resp.Content)
	}
	if caller.name != "codex" {
		t.Fatalf("tool = %q", caller.name)
	}
	if caller.args["model"] != "gpt-5.4" {
		t.Fatalf("model arg = %#v", caller.args["model"])
	}
	if !strings.Contains(caller.args["prompt"].(string), `"Name":"read_file"`) {
		t.Fatalf("prompt does not contain tool spec: %q", caller.args["prompt"])
	}
	if provider.threadID("run-1") != "thread-1" {
		t.Fatalf("threadID = %q", provider.threadID("run-1"))
	}
}

func TestCodexCLIProvider_ContinuesExistingThread(t *testing.T) {
	caller := &stubCodexCaller{
		resp: &codexToolResponse{
			Content:  `{"content":"","reasoning_content":"inspect","tool_calls":[{"id":"","name":"read_file","arguments":{"path":"README.md"}}]}`,
			ThreadID: "thread-1",
		},
	}
	provider := &CodexCLIProvider{
		model:   "gpt-5.4",
		caller:  caller,
		threads: map[string]string{"run-1": "thread-1"},
	}

	ctx := agent.WithRunContext(context.Background(), "run-1")
	resp, err := provider.GenerateContent(ctx, "sys", nil, nil)
	if err != nil {
		t.Fatalf("GenerateContent() error = %v", err)
	}
	if caller.name != "codex-reply" {
		t.Fatalf("tool = %q", caller.name)
	}
	if caller.args["threadId"] != "thread-1" {
		t.Fatalf("threadId arg = %#v", caller.args["threadId"])
	}
	if len(resp.ToolCalls) != 1 || resp.ToolCalls[0].Name != "read_file" {
		t.Fatalf("ToolCalls = %+v", resp.ToolCalls)
	}
	if resp.ToolCalls[0].ID == "" {
		t.Fatal("expected autogenerated tool call id")
	}
}

func TestCodexCLIProvider_GenerateContentSurfacesCallerError(t *testing.T) {
	provider := &CodexCLIProvider{
		model:   "gpt-5.4",
		caller:  &stubCodexCaller{err: errors.New("boom")},
		threads: make(map[string]string),
	}

	_, err := provider.GenerateContent(context.Background(), "sys", nil, nil)
	if err == nil || !strings.Contains(err.Error(), "codex mcp call failed") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCodexCLIProvider_GenerateContentSurfacesToolError(t *testing.T) {
	provider := &CodexCLIProvider{
		model: "gpt-5.4",
		caller: &stubCodexCaller{resp: &codexToolResponse{
			Content: "denied",
			IsError: true,
		}},
		threads: make(map[string]string),
	}

	_, err := provider.GenerateContent(context.Background(), "sys", nil, nil)
	if err == nil || !strings.Contains(err.Error(), "codex mcp tool returned an error") {
		t.Fatalf("unexpected error: %v", err)
	}
}
